services:
  backend-kowork:
    build:
      context: ..
    container_name: backend-kowork
    volumes:
      - ..:/app  
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    environment:
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DOMAIN=${DOMAIN}
      - CELERY_BROKER_URL=redis://redis-kowork:6379/0
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:${DJANGO_PORT}"]
    networks:
      - app-network-kowork
    depends_on:
      - db-kowork


  nginx-kowork:
    image: nginx:latest
    container_name: nginx-kowork
    ports:
      - "8051:8051"
    volumes:
      - ../docker_compose/nginx.kowork.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-kowork
      - frontend-kowork
    networks:
      - app-network-kowork

  frontend-kowork:
    build:
      context: ../frontend
    container_name: frontend-kowork
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    depends_on:
      - backend-kowork
    networks:
      - app-network-kowork
    environment:
      - REACT_APP_HOST=${HOST}

  db-kowork:
    image: postgres:13
    container_name: postgres-kowork
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network-kowork

  redis-kowork:
    image: redis:alpine
    container_name: redis-kowork
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network-kowork

  celery-worker-kowork:
    build:
      context: ..
    command: celery -A backend worker -l info
    volumes:
      - ..:/app
    environment:  
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db-kowork
      - DB_PORT=${DB_PORT}
      - CELERY_BROKER_URL=redis://redis-kowork:6379/0
    networks:
      - app-network-kowork
    depends_on:
      - db-kowork
      - redis-kowork

  celery-beat-kowork:
    build:
      context: ..
    command: celery -A backend beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ..:/app
    environment: 
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db-kowork
      - DB_PORT=${DB_PORT}
      - CELERY_BROKER_URL=redis://redis-kowork:6379/0
    networks:
      - app-network-kowork
    depends_on:
      - db-kowork
      - redis-kowork


  flower-kowork:
    build:
      context: ..
    command: celery -A backend flower --port=5555
    environment:
    - CELERY_BROKER_URL=redis://redis-kowork:6379/0
    ports:
      - "5555:5555"
    networks:
      - app-network-kowork
    depends_on:
      - celery-worker-kowork

volumes:
  redis_data:
  postgres_data:

networks:
  app-network-kowork:
    driver: bridge