events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # Kowork Server
    server {
        listen 8051;
        server_name localhost;

        location /api/v1/ {
            proxy_pass http://kowork-backend:8000/api/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            client_max_body_size 45M;
        }

        location /static_back/ {
            proxy_pass http://kowork-backend:8000/static_back/;
            proxy_set_header Host $host;
        }

        location /media/ {
            proxy_pass http://kowork-backend:8000/media/;
            proxy_set_header Host $host;
        }

        location /admin/ {
            proxy_pass http://kowork-backend:8000/admin/;
            proxy_set_header Host $host;
        }

        location /swagger/ {
            proxy_pass http://kowork-backend:8000/swagger/;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://kowork-frontend:3000/;
            proxy_set_header Host $host;
        }
    }

    # Coffee Server
    server {
        listen 8052;
        server_name localhost;



        location /api/v1/ {
            proxy_pass http://coffee-backend:8000/api/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            client_max_body_size 45M;
        }

        location /static_back/ {
            proxy_pass http://coffee-backend:8000/static_back/;
            proxy_set_header Host $host;
        }

        location /media/ {
            proxy_pass http://coffee-backend:8000/media/;
            proxy_set_header Host $host;
        }

        location /admin/ {
            proxy_pass http://coffee-backend:8000/admin/;
            proxy_set_header Host $host;
        }

        location /swagger/ {
            proxy_pass http://coffee-backend:8000/swagger/;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://coffee-frontend:3000/;
            proxy_set_header Host $host;
        }
    }

    server {
        listen 8053;
        server_name localhost;

        location /api/v1/ {
            proxy_pass http://clean-backend:8000/api/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            client_max_body_size 45M;
        }

        location /static_back/ {
            proxy_pass http://clean-backend:8000/static_back/;
            proxy_set_header Host $host;
        }

        location /media/ {
            proxy_pass http://clean-backend:8000/media/;
            proxy_set_header Host $host;
        }

        location /admin/ {
            proxy_pass http://clean-backend:8000/admin/;
            proxy_set_header Host $host;
        }

        location /swagger/ {
            proxy_pass http://clean-backend:8000/swagger/;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://clean-frontend:3000/;
            proxy_set_header Host $host;
        }
    }
}