# Generated by Django 5.1.6 on 2025-02-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("worker", "Worker"), ("supervisor", "Supervisor")],
                max_length=20,
                null=True,
            ),
        ),
    ]
