# Generated by Django 5.1.6 on 2025-02-13 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0002_alter_customuser_email_alter_customuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
    ]
