# Generated by Django 5.1.6 on 2025-02-13 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0003_remove_customuser_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
    ]
