# Generated by Django 5.1.6 on 2025-02-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_alter_work_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
