# Generated by Django 5.1.6 on 2025-02-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0005_alter_work_name_alter_work_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="worker_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
