# Generated by Django 5.1.6 on 2025-03-02 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0006_work_worker_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="status",
        ),
    ]
