# Generated by Django 4.2.20 on 2025-03-16 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_app", "0007_remove_object_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="object",
            options={"verbose_name": "Объект", "verbose_name_plural": "Объекты"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Оценка", "verbose_name_plural": "Оценки"},
        ),
        migrations.AlterModelOptions(
            name="work",
            options={"verbose_name": "Задача", "verbose_name_plural": "Задачи"},
        ),
        migrations.AlterModelOptions(
            name="workimage",
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.AlterField(
            model_name="object",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="object",
            name="deadline",
            field=models.DateTimeField(verbose_name="Срок сдачи"),
        ),
        migrations.AlterField(
            model_name="object",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="object",
            name="qr_code",
            field=models.URLField(blank=True, null=True, verbose_name="QR код"),
        ),
        migrations.AlterField(
            model_name="object",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата начала"
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="supervisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervised_objects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="task_description",
            field=models.TextField(verbose_name="Описание задачи"),
        ),
        migrations.AlterField(
            model_name="object",
            name="worker",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_objects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Работнки",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(verbose_name="Оценка"),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата оценки"),
        ),
        migrations.AlterField(
            model_name="review",
            name="supervisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто оценил",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="work",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.work",
                verbose_name="Работа",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="work",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время окончания"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="id",
            field=models.BigAutoField(
                primary_key=True, serialize=False, verbose_name="Id"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.object",
                verbose_name="Объект",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время начала"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Работник",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="worker_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий работника"
            ),
        ),
        migrations.AlterField(
            model_name="workimage",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="workimage",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата загрузки"),
        ),
        migrations.AlterField(
            model_name="workimage",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.work",
                verbose_name="Работа",
            ),
        ),
        migrations.CreateModel(
            name="WorkStatic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "worker_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий работника"
                    ),
                ),
                (
                    "repeat_every",
                    models.CharField(
                        choices=[
                            ("15m", "Каждые 15 минут"),
                            ("20m", "Каждые 20 минут"),
                            ("30m", "Каждые 30 минут"),
                            ("1h", "Каждый час"),
                            ("2h", "Каждые два часа"),
                            ("3h", "Каждые три часа"),
                            ("5h", "Каждые 5 часов"),
                            ("daily", "Каждый день"),
                            ("workday", "Каждый рабочий день"),
                            ("weekend", "Каждые выходные"),
                            ("weekly", "Раз в неделю"),
                            ("monthly", "Раз в месяц"),
                        ],
                        max_length=10,
                        verbose_name="Повторять каждые",
                    ),
                ),
                (
                    "daily_start_time",
                    models.TimeField(verbose_name="Время начала выполнения"),
                ),
                (
                    "daily_end_time",
                    models.TimeField(verbose_name="Время окончания выполнения"),
                ),
                (
                    "start_date",
                    models.DateTimeField(verbose_name="Дата начала выполнения"),
                ),
                (
                    "end_date",
                    models.DateTimeField(verbose_name="Дата окончания выполнения"),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.object",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Работник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон задачи",
                "verbose_name_plural": "Шаблоны задач",
            },
        ),
        migrations.AddField(
            model_name="work",
            name="work_static",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_app.workstatic",
                verbose_name="Шаблон задачи",
            ),
        ),
    ]
